importing libraries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import joblib

LOAD DATASET

In [19]:
df=pd.read_csv("solar_power_output.csv")
df.head()
df.tail()

     temperature   humidity  solar_irradiance  wind_speed  solar_power_output
495    18.833806  27.326566        701.391519    6.569552          352.480220
496    24.591403  93.385086        657.541311    9.566146          326.834297
497    11.943366  30.945490        517.144639    0.689580          259.133251
498    34.359870  96.018988        441.807202    0.570547          223.778239
499    34.655269  55.680462        877.000285    2.821871          435.410369

In [18]:
df.isnull().sum()

temperature           0
humidity              0
solar_irradiance      0
wind_speed            0
solar_power_output    0
dtype: int64

select features and target variable

In [21]:
X=df[['temperature','humidity','solar_irradiance','wind_speed']]
Y=df['solar_power_output']
X
Y

0      128.101772
1      290.911789
2      442.336390
3      380.261988
4      415.931953
          ...
495    352.480220
496    326.834297
497    259.133251
498    223.778239
499    435.410369
Name: solar_power_output, Length: 500, dtype: float64

split the dataset into training nd test sets(80%train,20%test)

In [26]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.8,random_state=42)

In [27]:
X_test

     temperature   humidity  solar_irradiance  wind_speed
361    26.082205  56.263107        289.595970    6.561618
73     30.386536  69.766936        116.086541    8.627971
374    11.779716  22.030908        322.507967    7.328015
155    16.051382  30.206424        777.444976    9.369578
104    32.689162  29.650870        995.417040    0.694238
..           ...        ...               ...         ...
347    11.132600  99.749940        433.934887    1.974705
86     28.240154  26.069066        652.070250    6.951446
75     28.225179  95.961650        484.995820    0.957146
438    27.656056  29.420087        281.668107    4.982557
15     14.585113  22.109358        932.723486    0.075629

[100 rows x 4 columns]

In [28]:
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

predicting the solar power output on yhe test set

In [38]:
y_pred=model.predict(X_test)
y_pred

array([145.57713107,  58.80813607, 162.02529472, 389.82145928,
       499.91950594, 201.0282157 , 280.32773311, 343.94995963,
       207.65845171, 274.08855807, 270.4758993 ,  71.45181397,
       429.2717113 , 474.93452177, 131.00879232, 488.72382531,
       351.97648481,  66.01156114, 286.53039285, 315.26996554,
       156.25649583, 217.68415494, 328.50926609, 456.09724416,
       224.5996492 , 343.33441394, 258.65661936, 253.27035924,
       487.33886964, 488.13938702, 352.87341423, 139.35221981,
       486.2457442 , 166.59050109, 443.99714231, 498.93693591,
       440.23818941, 184.21480104, 497.81182991, 239.22808162,
       345.26650268, 281.34107991, 215.84679473, 472.53738059,
       105.19383876, 353.92961078, 132.62179771, 496.30985098,
       472.03357268, 464.32390435,  68.39576647, 337.05784428,
       271.45779664, 142.00782194, 330.57420011, 209.16463829,
       431.33413852, 460.5254782 , 271.68335513, 148.17216826,
       322.32496321, 189.54364635, 148.80585848,  54.32626697,
       477.68708932, 193.09857442, 327.78450176, 155.94903389,
       486.49330331,  81.90369754, 249.1025331 , 257.83534344,
       494.00652549, 228.57425188, 379.22282528, 370.0548375 ,
       320.35938503, 181.0579938 , 469.88218569,  72.05722784,
       329.76422063, 237.83607462, 394.78456359, 336.13041583,
       123.75761569, 474.89224919, 482.2744928 , 289.41809558,
       296.55227317, 113.97247379, 226.40379581, 443.74657838,
       330.25021256, 490.55448237, 281.92908425, 214.43598619,
       328.26740398, 241.67895954, 142.67690408, 467.08839039])

evaluate the model performance

In [39]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.0
R-squared: 1.0